name: ci-test

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  build:
    name: style including testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: install lib npm
        run: npm ci
      
      - name: testing
        if: ${{ github.event_name == 'push' }}
        run: npm run test

      - name: style code
        run: npm run style